### ISSUE TITLE
protractor-flake doesn't run tests if suite is not specified

### ISSUE THREAD

**Issue by fubha** [NickTomlin/protractor-flake#104]
- Operating system and version = MacOS 10.14.2
- Node.js version = 8.9.0
- Protractor version = 5.1.2
- Protractor flake version = 3.3.0

```
var protractorFlake = require('protractor-flake');
var suites = process.argv.splice(2);

protractorFlake({
	protractorPath: './node_modules/.bin/protractor',
	maxAttempts: 3,
	protractorArgs: ['./config.js', suites]
}, function(status) {
	process.exit(status);
});
```

If I pass suites in the command then it runs the specified suites successfully. 
`node config/run-protractor.js --suite=suite1,suite2`

But if I don't pass any suite then it gives an error.
`node config/run-protractor.js`

Error:
`Error: Error: more than one config file specified`

Is there any solution for this? I need both the scenarios to work as I want to run all the suites usually but I want to run specific suites in certain cases as well.

**Comment by NickTomlin** [comment]
I'm surprised that it works with the suites specified as an array, but `protractorArgs` should be a flat array of options and not contain nested arrays. 

I've gotten your example to run both ways locally by spreading `suites` into protractor args. E.g.:

```
protractorArgs: ['./config.js', suites] // ['./config.js', ['--suites=one,two']]
```

changes to

```
protractorArgs: ['./config.js', ...suites] //  ['./config.js', '--suites=one,two']
```

Here's my [repository](https://github.com/NickTomlin/protractor-flake-issue-104) with the fix in place.


If that makes sense I think there's still a takeaway here in that protractor-flake could do a better job of warning when invalid options are specified

**Comment by fubha** [comment]
Thanks @NickTomlin. It's working fine with the spread operator `...`.

**Comment by NickTomlin** [comment]
Great! I'm going to close this. I'll make a note to investigate clearer directions on the type of `protractorArgs` in the future
