### ISSUE TITLE
"Protractor is not found"

### ISSUE THREAD

**Issue by johntran** [NickTomlin/protractor-flake#12]
Hi there!

I have protractor nested in "node_modules/protractor"  and ".bin/protractor". 

I go to my project folder and run "protractor-flake"

I get the error "Cannot find module 'protractor'".

How can I debug from here?

Thanks!

**Comment by NickTomlin** [comment]
Interesting, that definitely should not be happening. Thanks for bringing this up. To help troubleshoot, can you give me a few details: 
- Your operating system
- Your node version
- Your protractor version
- Your protractor-flake version

Does running programmatically work?

**Comment by johntran** [comment]
> OS: OS X 10.10.2
> Node: v0.12.7
> Protractor: v2.1.0
> Protractor Flake: v1.0.1

When doing "npm list -g", I got this error: 

> npm ERR! missing: protractor@2.x, required by protractor-flake@1.0.1

I did "npm install -g protractor" and ran "protractor-flake" and got below:

> Re-running tests: test attempt 2
> Re-running the following test files:
> 
> [launcher] Process exited with error code 1
> Re-running tests: test attempt 3
> Re-running the following test files:
> 
> [launcher] Process exited with error code 1"

How do I move forward from here?
Thanks! :)

**Comment by NickTomlin** [comment]
Thanks for the info! Would it be possible to see your protractor config file? Seems like something might be wrong there. 

Protractor does need to be installed. It should be automatically installed when using NPM < 3, which is odd :\

**Comment by johntran** [comment]
My protractor.conf.js file:

> 'use strict';
> 
> var paths = require('./.yo-rc.json')['generator-gulp-angular'].props.paths;
> 
> exports.config = {
>  rootElement: 'html',
>  capabilities: {
>    'browserName': 'chrome',
>    'chromeOptions': {
>      args: ['--lang=en',
>      '--window-size=1024,768']
>    }
>  },
> 
>  specs: [paths.e2e + '/*_/_.spec.js'],
> 
>  baseUrl: 'http://localhost:8080',
> 
>  jasmineNodeOpts: {
>    showColors: true,
>    defaultTimeoutInterval: 30000
>  }
> };

**Comment by lynchblue** [comment]
Same issue here

**Comment by NickTomlin** [comment]
@lynchblue could I also get you to give the following detals: 
- Your operating system
- Your node version
- Your protractor version
- Your protractor-flake version

As well as your `protractor.conf.js` file

**Comment by lynchblue** [comment]
@NickTomlin I already fixed the issue. The problem was that I had removed the node_modules folder and then I had run <code>npm install</code> but I forgot to run <code>webdriver-manager update</code> in order to download the webdriver jar. Therefore the tests couldn't be run and no output was shown.

**Comment by johntran** [comment]
Is there a project you can show with protractor flake installed? Maybe my config is off somehow.

**Comment by NickTomlin** [comment]
@johntran I don't have an open-source project to show you but you can look at the configs included in the [test suite](https://github.com/NickTomlin/protractor-flake/blob/master/test/support/protractor-config/protractor.conf.js).

**Comment by johntran** [comment]
@NickTomlin Good news! You can close this issue.

I tried running my protractor with sharding and I got this error:

> [chrome #1-11]     throw new Error('No selenium server jar found at the specified ' +
> [chrome #1-11]     ^
> [chrome #1-11]
> [chrome #1-11] Error: No selenium server jar found at the specified location  (/usr/local/lib/node_modules/protractor/selenium/selenium-server-standalone-2.45.0.jar). Check that the version number is up to date.

Googling this issue gets this link: http://stackoverflow.com/questions/29219075/webdriver-unable-to-create-session-with-phantomjs

I ran

> webdriver-manager update

and it works! 

I'm using protractor-flake at the company I'm working at, and your library allows us to have continuous integration on our front end. 

Thank you so much!

**Comment by NickTomlin** [comment]
@johntran glad you figured it out! Thanks for reporting back.

**Comment by qiangli** [comment]
root cause for the record: check if protractor and protractor-flake are installed into different locations (just as was originally reported) especially if you have multiple copies installed in node_modules, globally in /usr/bin or usr/local/bin. protractor-flake will get confused.

**Comment by NickTomlin** [comment]
@qiangli thanks for closing the loop on this. 

I'd welcome a pull request that prevents this issue you if have something in mind!
