### ISSUE TITLE
Not working with latest version of protractor - 2.3.0

### ISSUE THREAD

**Issue by el-davo** [NickTomlin/protractor-flake#13]
Hi 

We have been using your plugin for a few weeks now with version 2.2.0 of protractor and it has been working perfectly. After upgrading to latest version we now see that there is an issue when the tests try and re-run. We get an error like below. Am not sure what is causing it?

WARNING - pattern C:\GIT\titan-ui\test\e2e\integration\data-management\project-workspace\projectAssetsSpec.js did not match any files.
WARNING - pattern C:\GIT\titan-ui\test\e2e\integration\dashboard\dashboardSpec.js did not match any files.
WARNING - pattern C:\GIT\titan-ui\test\e2e\integration\data-management\project-workspace\projectUploadSpec.js did not match any files.
WARNING - pattern C:\GIT\titan-ui\test\e2e\integration\data-management\projects\projectsDashboardSpec.js did not match any files.

**Comment by NickTomlin** [comment]
Alas, it looks like this is an upstream issue with [protractor 2.3.0](https://github.com/angular/protractor/issues/2551) and windows paths. Are you using the cli version of protractor flake?

**Comment by el-davo** [comment]
Hi Nick.

Unfortunately not. We are using with node wrapped in a gulp task. Thanks for pointing to the root of the issue though

**Comment by el-davo** [comment]
Hi Nick.

I can confirm that this is now working in protractor 2.5.1. Please feel free to close. Awesome plugin btw

**Comment by NickTomlin** [comment]
Great. Glad to hear it! Thanks for updating!
