### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by zivSher** [NickTomlin/protractor-flake#14]
Hi,
I might missing something, but I didn't understand exactly how to use it programatically. where exactly do I put it?
is there an example of use?
Thanks a lot.

**Comment by NickTomlin** [comment]
There's an example in the README: 

```
var protractorFlake = require('protractor-flake');

protractorFlake({
  maxAttempts: 3,
  protractorArgs: []
}, function (status, output) {
  process.exit(status);
});
```

I currently use this inside of a gulp task that starts my server and then launches protractor via protractor-flake.

**Comment by zivSher** [comment]
thanks. i saw it earlier but still not sure how exactly to use it. should I put it in the spec file or the conf file? and how exactly to use it?
BTW, I don't use grunt or gulp.
Thanks.

**Comment by NickTomlin** [comment]
You use it to launch protractor, so you include in a file outside of your specs or config. E.g. you could create a file called `run-protractor.js` with the contents above and run `node run-protractor.js` which would run protractor wrapped by protractor-flake.

**Comment by NickTomlin** [comment]
I'm going to go ahead and close this. Please feel to reach out in the [gitter](https://gitter.im/NickTomlin/protractor-flake?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel with more questions
