### ISSUE TITLE
Test for and handle multiCapabilities

### ISSUE THREAD

**Issue by NickTomlin** [NickTomlin/protractor-flake#2]
We need to add coverage for spes run with multiCapabilities set. See #1

**Comment by odaems** [comment]
I actually tried to do this yesterday, but couldn't finish in time. 
Ideally you would only want to repeat the spec in the capability it failed in, currently it repeats the spec for capabilities defined in the initial protractor conf.

**Comment by NickTomlin** [comment]
We now have test coverage at the unit level for this, but it would be good to add some integration tests that actually run protractor with multiCapabilities. I'll leave this open for now.

**Comment by NickTomlin** [comment]
I'm going to close this for now. We can backfill test coverage later if we need it.
