### ISSUE TITLE
Handle webdriver timeouts

### ISSUE THREAD

**Issue by guilhotarras** [NickTomlin/protractor-flake#21]
Hello,
I am trying to use protractor-flake to rerun some failed scenarios that are failing sometimes because my selenium grid gives a timeout when forwards some tests to the nodes.
When this occurs, I get this log:

`03:43:15.738 [chrome #01-34] WebDriverError: Error forwarding the new session Error forwarding the request Read timed out
03:43:15.738 [chrome #01-34]     at WebDriverError (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/error.js:26:26)
03:43:15.738 [chrome #01-34]     at Object.checkLegacyResponse (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/error.js:580:13)
03:43:15.738 [chrome #01-34]     at /var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/lib/webdriver.js:64:13
03:43:15.738 [chrome #01-34]     at Promise.invokeCallback_ (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/lib/promise.js:1329:14)
03:43:15.738 [chrome #01-34]     at TaskQueue.execute_ (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/lib/promise.js:2790:14)
03:43:15.738 [chrome #01-34]     at TaskQueue.executeNext_ (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/lib/promise.js:2773:21)
03:43:15.738 [chrome #01-34]     at /var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/lib/promise.js:2652:27
03:43:15.738 [chrome #01-34]     at /var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/lib/promise.js:639:7
03:43:15.738 [chrome #01-34]     at process._tickCallback (node.js:405:9)
03:43:15.738 [chrome #01-34] From: Task: WebDriver.createSession()
03:43:15.738 [chrome #01-34]     at acquireSession (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/lib/webdriver.js:62:22)
03:43:15.739 [chrome #01-34]     at Function.createSession (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/lib/webdriver.js:295:12)
03:43:15.739 [chrome #01-34]     at Builder.build (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/builder.js:458:24)
03:43:15.739 [chrome #01-34]     at [object Object].DriverProvider.getNewDriver (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/protractor/built/driverProviders/driverProvider.js:42:27)
03:43:15.739 [chrome #01-34]     at [object Object].Runner.createBrowser (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/protractor/built/runner.js:203:37)
03:43:15.739 [chrome #01-34]     at /var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/protractor/built/runner.js:293:21
03:43:15.739 [chrome #01-34]     at _fulfilled (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/q/q.js:834:54)
03:43:15.739 [chrome #01-34]     at self.promiseDispatch.done (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/q/q.js:863:30)
03:43:15.739 [chrome #01-34]     at Promise.promise.promiseDispatch (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/q/q.js:796:13)
03:43:15.739 [chrome #01-34]     at /var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/q/q.js:556:49`

So on the final log, I have checked that these type of tests (failed with exit code 1) are not rerunned.

`03:19:06.063 [launcher] chrome #01-6 failed with exit code: 1
03:19:06.063 [launcher] chrome #01-12 passed
03:19:06.064 [launcher] chrome #01-13 passed
03:19:06.064 [launcher] chrome #01-14 passed
03:19:06.064 [launcher] chrome #01-11 failed with exit code: 1
03:19:06.064 [launcher] chrome #01-15 passed
03:19:06.064 [launcher] chrome #01-16 passed
03:19:06.064 [launcher] chrome #01-17 passed
03:19:06.064 [launcher] chrome #01-18 passed
03:19:06.064 [launcher] chrome #01-19 passed
03:19:06.064 [launcher] chrome #01-20 passed
03:19:06.064 [launcher] chrome #01-21 passed
03:19:06.064 [launcher] chrome #01-23 passed
03:19:06.064 [launcher] chrome #01-22 failed with exit code: 1
03:19:06.064 [launcher] chrome #01-25 passed
03:19:06.064 [launcher] chrome #01-24 failed with exit code: 1
03:19:06.064 [launcher] chrome #01-26 passed
03:19:06.064 [launcher] chrome #01-27 passed
03:19:06.064 [launcher] chrome #01-28 passed
03:19:06.064 [launcher] chrome #01-29 passed
03:19:06.065 [launcher] chrome #01-30 passed
03:19:06.065 [launcher] chrome #01-31 passed
03:19:06.065 [launcher] chrome #01-33 passed
03:19:06.065 [launcher] chrome #01-34 failed 1 test(s)
03:19:06.065 [launcher] chrome #01-35 failed 1 test(s)
03:19:06.065 [launcher] chrome #01-36 passed
03:19:06.065 [launcher] chrome #01-32 failed with exit code: 1
03:19:06.065 [launcher] overall: 2 failed spec(s) and 5 process(es) failed to complete
03:19:06.065 [launcher] Process exited with error code 100
03:19:06.072 Re-running tests: test attempt 2
03:19:06.072 Re-running the following test files:
03:19:06.072 /var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/mock-tests/tests/account/desktop/my-tracks-1-spec.js
03:19:06.072 /var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/mock-tests/tests/account/desktop/my-tracks-2-spec.js`

The only ones that are re-runned are these -> (03:19:06.065 [launcher] chrome #01-34 failed 1 test(s)).

Please edit this comment to see the breaklines.

**Comment by NickTomlin** [comment]
Hi there!

I don't have any experience with Selenium Grid unfortunately. Protractor flake is very simplistic in that it just [parses](https://github.com/NickTomlin/protractor-flake/blob/master/src/failed-spec-parser.js#L12) the output of protractor looking for exceptions. If selenium grid is not outputting a stack trace in the format that protractor-flake is looking for it will not work. 

It looks like the Timeout error doesn't include a stack trace to the file, and not in that format, so it currently won't work. I think this would also be a problem for timeouts in non grid tests as well.

I don't have a great solution off the top of my head, but i'd be more than happy to accept a PR or try to find one with you.

**Comment by guilhotarras** [comment]
`04:39:44.056 [chrome #01-33] PID: 13612
04:39:44.056 [chrome #01-33] Specs: /var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/mock-tests/tests/account/desktop/my-tracks-0-spec.js
04:39:44.056 [chrome #01-33] 
04:39:44.056 [chrome #01-33] Using the selenium server at http://10.216.1.49:4444/wd/hub
04:39:44.056 [chrome #01-33] 
04:39:44.056 [chrome #01-33] /var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/error.js:26
04:39:44.056 [chrome #01-33]   constructor(opt_error) {
04:39:44.056 [chrome #01-33]                          ^
04:39:44.056 [chrome #01-33] WebDriverError: Error forwarding the new session Error forwarding the request Read timed out
04:39:44.056 [chrome #01-33]     at WebDriverError (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/error.js:26:26)
04:39:44.056 [chrome #01-33]     at Object.checkLegacyResponse (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/error.js:580:13)
04:39:44.056 [chrome #01-33]     at /var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/lib/webdriver.js:64:13
04:39:44.056 [chrome #01-33]     at Promise.invokeCallback_ (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/lib/promise.js:1329:14)
04:39:44.056 [chrome #01-33]     at TaskQueue.execute_ (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/lib/promise.js:2790:14)
04:39:44.056 [chrome #01-33]     at TaskQueue.executeNext_ (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/lib/promise.js:2773:21)
04:39:44.057 [chrome #01-33]     at /var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/lib/promise.js:2652:27
04:39:44.057 [chrome #01-33]     at /var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/lib/promise.js:639:7
04:39:44.057 [chrome #01-33]     at process._tickCallback (node.js:405:9)
04:39:44.057 [chrome #01-33] From: Task: WebDriver.createSession()
04:39:44.057 [chrome #01-33]     at acquireSession (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/lib/webdriver.js:62:22)
04:39:44.057 [chrome #01-33]     at Function.createSession (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/lib/webdriver.js:295:12)
04:39:44.057 [chrome #01-33]     at Builder.build (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/selenium-webdriver/builder.js:458:24)
04:39:44.057 [chrome #01-33]     at [object Object].DriverProvider.getNewDriver (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/protractor/built/driverProviders/driverProvider.js:42:27)
04:39:44.057 [chrome #01-33]     at [object Object].Runner.createBrowser (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/protractor/built/runner.js:203:37)
04:39:44.057 [chrome #01-33]     at /var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/protractor/built/runner.js:293:21
04:39:44.057 [chrome #01-33]     at _fulfilled (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/q/q.js:834:54)
04:39:44.057 [chrome #01-33]     at self.promiseDispatch.done (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/q/q.js:863:30)
04:39:44.057 [chrome #01-33]     at Promise.promise.promiseDispatch (/var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/q/q.js:796:13)
04:39:44.057 [chrome #01-33]     at /var/lib/go-agent-4/pipelines/FrontEnd-TVG4-Dev/workspace/tvg-tvg4-angular/tests/web-tests/node_modules/q/q.js:556:49
04:39:44.057 
04:39:44.057 [launcher] Runner process exited unexpectedly with error code: 1
04:39:44.057 [launcher] 0 instance(s) of WebDriver still running
04:39:44.058 [launcher] chrome #01-0 passed
04:39:44.058 [launcher] chrome #01-1 passed
04:39:44.058 [launcher] chrome #01-2 passed
04:39:44.058 [launcher] chrome #01-3 passed
04:39:44.058 [launcher] chrome #01-5 passed
04:39:44.058 [launcher] chrome #01-6 passed
04:39:44.058 [launcher] chrome #01-7 passed
04:39:44.058 [launcher] chrome #01-4 failed with exit code: 1
04:39:44.058 [launcher] chrome #01-9 passed
04:39:44.058 [launcher] chrome #01-10 passed
04:39:44.058 [launcher] chrome #01-8 failed with exit code: 1
04:39:44.058 [launcher] chrome #01-12 passed
04:39:44.058 [launcher] chrome #01-13 passed
04:39:44.058 [launcher] chrome #01-14 passed
04:39:44.058 [launcher] chrome #01-15 passed
04:39:44.058 [launcher] chrome #01-16 passed
04:39:44.059 [launcher] chrome #01-17 passed
04:39:44.059 [launcher] chrome #01-18 passed
04:39:44.059 [launcher] chrome #01-19 passed
04:39:44.059 [launcher] chrome #01-20 passed
04:39:44.059 [launcher] chrome #01-21 passed
04:39:44.059 [launcher] chrome #01-22 passed
04:39:44.059 [launcher] chrome #01-11 failed with exit code: 1
04:39:44.059 [launcher] chrome #01-24 passed
04:39:44.059 [launcher] chrome #01-25 passed
04:39:44.059 [launcher] chrome #01-26 passed
04:39:44.059 [launcher] chrome #01-27 passed
04:39:44.059 [launcher] chrome #01-23 failed with exit code: 1
04:39:44.059 [launcher] chrome #01-28 failed with exit code: 1
04:39:44.059 [launcher] chrome #01-30 passed
04:39:44.059 [launcher] chrome #01-31 passed
04:39:44.059 [launcher] chrome #01-32 passed
04:39:44.059 [launcher] chrome #01-29 failed with exit code: 1
04:39:44.060 [launcher] chrome #01-34 passed
04:39:44.060 [launcher] chrome #01-35 passed
04:39:44.060 [launcher] chrome #01-36 passed
04:39:44.060 [launcher] chrome #01-33 failed with exit code: 1
04:39:44.060 [launcher] overall: 7 process(es) failed to complete
04:39:44.060 [launcher] Process exited with error code 100
04:39:44.067 Re-running tests: test attempt 2
04:39:44.067 Re-running the following test files:
04:39:44.067 
04:39:44.264 [launcher] Running 2 instances of WebDriver
04:39:50.890 .
04:39:50.890 ------------------------------------
04:39:50.890 [chrome #01-0] PID: 13637`

This is the format that protractor and selenium grid are outputting.
It seems that protractor-flake does not find the those tests that are giving timeout errors.
That was the reason I needed protractor-flake, in order to rerun those timeout tests.
If you can find some solution for this, it would be great.
Thanks,

**Comment by NickTomlin** [comment]
I currently don't have the time to work on this feature, but i'd be happy to work alongside you as I can to implement it. I'm going to change the issue of this title to "handle webdriver timeouts"

Thanks!

**Comment by guilhotarras** [comment]
Ok thank you. When you have time, please ping me.
Regards

**Comment by guilhotarras** [comment]
Hi, another question is: When protractor-flake re-runs failed tests, the pipeline where they run is going to be green ? I ask this because it is very important to have a quick visual about the state of the pipeline where the tests are runned.

**Comment by NickTomlin** [comment]
I'm not sure what you mean by the pipeline being green. Could you give some more details on that?

**Comment by guilhotarras** [comment]
I run my tests on GO server, that has a pipeline with a task that runs the tests. When the tests are successful, that pipeline stays green (green bar), when it doesn't, it stays red.

**Comment by NickTomlin** [comment]
I don't think this should affect the pipeline then, it should only "fail" when the retries have all run unsuccessfully.

**Comment by guilhotarras** [comment]
Ok .... have you already have a solution for this webdriver timeouts ?

**Comment by NickTomlin** [comment]
I do not have a solution. I'm not going to be actively working on this feature. If you would like a fix you are free to implement one via a PR though 😄

**Comment by FinKingma** [comment]
I was having the same problem. However, when using sharding, and the Specs are described at the start of each run, it is quite easy to create a fix.
I added a PR that collects all tests in an array of tests, and then checks each test for a passing signal (0 failure), and in all other cases it will add the file to the list to re-run. This way all error states are captured as well, because 0 failure will not be found.
