### ISSUE TITLE
Provide verbose mode

### ISSUE THREAD

**Issue by z-boy** [NickTomlin/protractor-flake#22]
Hi,

it would be nice to have the possibility to start protractor-flake in verbose mode. 
When I e.g. install protractor and I forget to download the selenium-servier binaries I get a standard pretty understandable error message once I start my e2e tests. But when I start my tests with protractor-flake instead, this message will be swallowed and the user is stuck. I'm also not able to pass the --verbose flag to protractor alongside the execution of protractor-flake or am I missing something here?

`protractor-flake --max-attempts=3 -- protractor-config.js --verbose`

Thanks!

**Comment by NickTomlin** [comment]
`--verbose` should get passed through but I think you are right in that we _do_ swallow the output. 

I think we should definitely pursue this, great catch!

I'll try to work on this in my spare time but feel free to submit a PR!

**Comment by NickTomlin** [comment]
This should be solved (or at least made better by ) https://github.com/NickTomlin/protractor-flake/commit/831672ad0f0a19626230b823f3704d8c69f1c8de. I'm going to go ahead and close this.
