### ISSUE TITLE
Fix to handle lowercase drive letters on Windows

### ISSUE THREAD

**Issue by molasses0** [NickTomlin/protractor-flake#23]
When I run protractor flake on Jenkins it is not finding failed specs as the log is listing the Windows drive letter in lowercase.
eg. d:\workspace\blah\blah.js

Can you please update the FAILED_LINES regex to be case insensitive?
let FAILED_LINES = /at (?:[object Object]|Object).<anonymous> ((([A-Z]:\)?._?):._)/gi

Or to include lowercase drive letters?
let FAILED_LINES = /at (?:[object Object]|Object).<anonymous> ((([A-Za-z]:\)?._?):._)/g

https://github.com/NickTomlin/protractor-flake/blob/master/src/failed-spec-parser.js#L12

Thanks

**Comment by NickTomlin** [comment]
Great catch! Let's go with handling lowercase drive names `[A-Za-z]`. 

I can try to get this patched up later today, but if you want to submit a PR (with a test) that would be much appreciated.

**Comment by NickTomlin** [comment]
This has been released. Let me know if that hasn't resolved things for you!
