### ISSUE TITLE
TypeError: list.split is not a function

### ISSUE THREAD

**Issue by wswebcreation** [NickTomlin/protractor-flake#35]
**Version protractor-flake:** 2.0.1
**Version protractor:** 3.2.2

**Situation:**
We use a custom grunt taskmanager to create protractor tasks. In those tasks we provide the `steps:` that need to be run.
When `protractor-flake` provides the array of failed specs `protractor` is run again for the second time. `protractor` then fails with this error

```
Re-running tests: test attempt 2
Re-running the following test files:
/Users/wswebcreation/test/e2e/features/functional/another.flakey.feature
/Users/wswebcreation/protractor-flake/node_modules/protractor/lib/cli.js:113
  var patterns = list.split(',');
                      ^

TypeError: list.split is not a function
    at processFilePatterns_ (/Users/wswebcreation/protractor-flake/node_modules/protractor/lib/cli.js:113:23)
    at Object.<anonymous> (/Users/wswebcreation/protractor-flake/node_modules/protractor/lib/cli.js:121:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/wswebcreation/protractor-flake/node_modules/protractor/bin/protractor:5:1)
    at Module._compile (module.js:425:26)
```

**Cause:**
The `protractorArgs` array (see index.js file) holds two `--specs` and two paths to the specs. The original `--specs` from the taskmanager and the new added `--specs` by `protractor-flake` (`protractorArgs.push('--specs', specFiles.join(','));`). `protractor` only allows multiple specs when they are provided as a comma-separated set of files.

**Posible solution:**
In my opinion the initial provided set of specs are not needed now anymore, only the failed set of specs should be run.

```
// this piece of code in index.js
    if (specFiles.length) {
      protractorArgs = protractorArgs.filter((arg) => !/^--suite=/.test(arg))
      protractorArgs.push('--specs', specFiles.join(','))
    }
// should be changed by this
    if (specFiles.length) {
      protractorArgs = protractorArgs.filter((arg) => !/^--suite=/.test(arg))
      var specIndex = protractorArgs.indexOf('--specs')
      if(specIndex > -1){
        protractorArgs.splice(specIndex, 2)
      }
      protractorArgs.push('--specs', specFiles.join(','))
    }
```

If agreed I can provide a PR for this

**Comment by NickTomlin** [comment]
I think this makes sense! I wonder if we could just do a better job of cleaning up the arguments with a helper function (since we want to drop anything that specifies `--suite` or `--specs` on re-run and replace them with just `specs`?

A pr would be welcome!

**Comment by wswebcreation** [comment]
I'll make a PR for the '--specs'

We're not working with '--suites' so I don't know what I would break by making a generic helper for it.

**Comment by NickTomlin** [comment]
Sounds good. I think we'll also want to incorporate `--suites` but that's something that I can focus on.

**Comment by wswebcreation** [comment]
PR fixed, can be closed
