### ISSUE TITLE
Integration with grunt-protractor-runner

### ISSUE THREAD

**Issue by wlsf82** [NickTomlin/protractor-flake#39]
Is it possible to integrate protractor-flake with grunt-protractor-runner (https://www.npmjs.com/package/grunt-protractor-runner)?

**Comment by wswebcreation** [comment]
Hi @wlsf82,

Yes it is possibile, but it should be a PR for `grunt-protractor-runner`. They should provide the command line parameter like `--protractor-flake --attemps=3` and create an implementation for it.

Hope this answers your question.
