### ISSUE TITLE
About making flake message more visible

### ISSUE THREAD

**Issue by sul4bh** [NickTomlin/protractor-flake#47]
The messages/logs from protractor-flake are hard to notice in long stream of logs. Is there a way to make the messages more visible?

Some of the messages that I am talking about are:
'Re-running tests: test attempt ' + testAttempt + '\n'
'Re-running the following test files:\n'

I am thinking we could have an option to add colors to various log levels? Most of the messages generated by flake are 'info' messages. We could add an option to make 'info' yellow? Or underline?

Let me know if you have any other ideas. I can work on creating a PR for adding color if you like it.

**Comment by wswebcreation** [comment]
Hi @sul4bh,

Sounds like a good idea. We can use for example [chalk](https://github.com/chalk/chalk) for this. On the other hand, colors are not always seen in CI solutions like Jenkins.
Can you create a PR for it to share your idea?

Grtz
Wim

**Comment by NickTomlin** [comment]
👍  would love to see a PR for this

(and also to to ensuring that we allow for disabling this for CI/Automated solutions that may not support colors)
