### ISSUE TITLE
Parsers do not validate if a testrunner's output is parsable

### ISSUE THREAD

**Issue by sul4bh** [NickTomlin/protractor-flake#50]
The parsers might need some type of smoke test/check to determine if the output of a testrunner is parsable or not. Probably show a warning message that the parser might not be able to accurately parse an output if the smoke test fails?

I ran into a case where the test-runner output would partially match `multi` parser's regex. The parser was able to extract the spec filenames but was unable to determine accurately if the spec passed or failed. Because of this, the parser would mark all the spec files as 'failed' and rerun all the spec file.

If you think this might be a useful feature, I can work towards a PR for it.

**Comment by wswebcreation** [comment]
Hi @sul4bh,

A PR to optimize the parser is always welcome. Can you also give a log example about the problem you were facing?

Tnx in advance

Wim

**Comment by sul4bh** [comment]
Not sure if I can share the full log but it was my bad using the `multi` parser. Using `standard` parser fixed my immediate issue.

I will look into adding basic test for `parser` probably this weekend.

**Comment by sul4bh** [comment]
@wswebcreation Ran into standard parser not parsing the errors correctly. See the following:
https://regex101.com/r/yfRPFL/2

**Comment by wswebcreation** [comment]
Tnx

Sorry for the late reaction, was very busy. Will look at it this weekend.

**Comment by wswebcreation** [comment]
Hi @sul4bh ,

Just overwritten you log, sorry. What's the error you get when you use the multiple parser? If you look at [this](https://github.com/NickTomlin/protractor-flake/blob/19ca355198ce7b7f784c80a51a14e09fc8e6d213/test/unit/support/fixtures/sharded-output-single-failure.txt) log you will see that the standard parser also matches the jasminewd2 line, same error you had. 

I could reproduce it with your logging with the multi parser.

**Comment by sul4bh** [comment]
I encountered addition issues with standard parser. I wrote a custom parser to solve the issues. See here for the regex that I used: https://regex101.com/r/WIiUyk/3

**Comment by NickTomlin** [comment]
@sul4bh Glad to hear; I think a custom parser is appropriate for this use case. An ideal solution would be if we could interrogate each framework for the failed files/specs but using custom parsers to handle differences in formatting is the best approach now.

I'm going to go ahead and close this.
