### ISSUE TITLE
Message re-running test file, but still re-runs my other files

### ISSUE THREAD

**Issue by manholok** [NickTomlin/protractor-flake#57]
![screenshot_rerun](https://cloud.githubusercontent.com/assets/2269966/25660048/d43a55dc-300a-11e7-96ae-3871dec3a162.jpg)

Because of a timeout error not giving a stacktrace with a filename to work with, I've added a console.error(error.stack) in the afterEach() in every e2e file. The error log will appear when the currentSpec.failedExpectations is filled.

Before, it would get the message that it had a timeout and could not find a spec,  because of the stacktrace not giving any...

But now, as seen in the screenshot, it finds the file, but still runs my other e2e files AFTER finishing the one that was found. It will start my workout-overview.e2e and after that, will continue with another e2e file, that was not mentioned in the re-run list.

Does anyone have any idea, how I can look into the specs that have been chosen by protractor-flake to re-run? Or any other idea how to try and debug/solve this problem.

my spec glob = [../src/test/integration/**/*.e2e.js]
is it maybe adding the found spec to this list? and not removing the glob? or something like that...

**Comment by NickTomlin** [comment]
Could you explain

> AFTER finishing the one that was found. It will start my workout-overview.e2e and after that, will continue with another e2e file, that was not mentioned in the re-run list.

In more detail? The logging means that protractor-flake [should be identifying the right tests](https://github.com/NickTomlin/protractor-flake/blob/master/src/index.js#L37) so perhaps there's an issue with how you are starting your tests?

Would it be possible to get you to reproduce this with an example?

**Comment by manholok** [comment]
I found my mistake. This was in my protractor config.

I exported my specs in the multicapabilities like this:

```
multiCapabilities = [		
      {		
        browserName: 'firefox',		
        marionette: 'true',		
        specs: [		
          specs		
        ]		
      }];
```

instead of:

```
exports.config = {
  specs: [ specs ]
}
```

I noticed the difference when I was comparing it with another config file. Now my tests are re-running correctly

**Comment by NickTomlin** [comment]
Glad to hear it! Thanks for reporting back!
