### ISSUE TITLE
protractor-flake within onPrepare function

### ISSUE THREAD

**Issue by beyaban** [NickTomlin/protractor-flake#58]
can i configure flake options within onPrepare function by protractor config?

**Comment by wswebcreation** [comment]
No, you can't run it like that. You can see protractor-flake as a wrapper around Protractor to read the log. This can't be done with the `onPrepare` of Protractor.

**Comment by NickTomlin** [comment]
👍  Protractor Flake is just a wrapper for executing `./node_modules/.bin/protractor` so you'll need to do all your flake configuration outside of protractor.
