### ISSUE TITLE
Protractor-flake:  duplicate tests in Allure report

### ISSUE THREAD

**Issue by klodiya** [NickTomlin/protractor-flake#61]
Hi Nick,

I was wondering if you had some experience with printing results of rerunning flake tests to Allure tool. After rerunning my tests 3 times, Allure will generate a report counting all failed tests and passed in the first run tests. I would like just to print failed tests in the last re-run. Maybe you have any ideas how to do so?

Thanks,
Tatiana

**Comment by NickTomlin** [comment]
Hi There, 

Unfortunately I'm not familiar with Allure (just took my first look and it seems very cool!). It looks like Allure provides a jasmine adapter but I'm assuming it has no way of differentiating duplicate output. 

I'd reach out to folks more familiar with Allure, they may be able to help clarify how to customize the framework to play nicely. Sorry to not be of much help! Good luck! 😄
