### ISSUE TITLE
Does not work for sharded setup

### ISSUE THREAD

**Issue by GuyMograbi** [NickTomlin/protractor-flake#62]
The current project I am on has passing builds even though some protractor test fails. 

After some investigation I found that if I remove parallelism, everything is consistent. 

Assuming 
 - I have 10 tests 
 - test 10 is flaky 
 - test 5 fails 
 - protractor is configured to shard the test 

```
    shardTestFiles: true
    maxInstances: 2
```

I suspect the following happens
 - test 5 fails
 - test 10 fails (overrides the failure for test 5 ?)
 - flake reruns test 10
 - test 10 passes the second time

==> everything seems fine but shouldn't because test 5 did not pass. 

Is it something I am doing wrong in the configuration?

**Comment by wswebcreation** [comment]
Hi @GuyMograbi ,

Can you provide some more info, for example:

- which parser do you use
- post your logging where you see this happen

Tnx in advance

**Comment by GuyMograbi** [comment]
I am not using any special parser.

I just see tests failing, but ignored by flake.

I bet it could easily be reproduced if we do something lie

Expect(2).toBe(Date.now()%2)

**Comment by NickTomlin** [comment]
Could provide more detailed output? This is going to be difficult to troubleshoot without looking at the logs; protractor flake is pretty dumb and just scrapes the output from protractor/your test framework so we can get a pretty clear idea of what is occurring. 

We don't track successful tests (just successful "runs") so an individual spec success shouldn't override a failure. This could be a failure in the standard parser to pick up `shardTestFiles` output though.

**Comment by wswebcreation** [comment]
@GuyMograbi 

Is this still valid?

**Comment by NickTomlin** [comment]
Going to close this because it's been a long while.
