### ISSUE TITLE
Protractor-flake doesn't rerun all specs with failed tests

### ISSUE THREAD

**Issue by klodiya** [NickTomlin/protractor-flake#65]
For example after the first run I have 46 tests failing from 22 specs. It prints and executes a list of only 11 specs.  What can be the reason for that?

**Comment by ghost** [comment]
What the solution ? i am trying to implement same. 
Flake file : 

#!/usr/bin/env node

/**
 * flake is a node script that uses protractor-flake to re-run failed tests. Note
 * that it reruns tests at the _file_ level, so if one test fails, it will rerun all
 * the tests in that file. Still... awesome.
 *
 * usage:
 * `./flake conf.js [other protractor args]`
 */
 //const rerun = require('./module');
 const protractorFlake = require('protractor-flake');

// skip first two passed args (node and self)
let protractorArgs = process.argv.splice(2);
protractorFlake({
        protractorPath: 'node_modules/.bin/protractor',
        maxAttempts: 2,
        parser: 'multi',
        nodeBin: 'node',
        color: 'magenta',
        protractorArgs: protractorArgs
    }, function(status, output) {
        process.exit(status);
    });

What will be right way to implement parser which will execute only failed test

**Comment by NickTomlin** [comment]
@Trisha1212 could you open a new issue with the test output? Typically this is due to a reporter or test framework tweak that is changing the output to an unexpected format. 

Also, you shouldn't need to use a wrapper scrip like the one that you've posted, the `protractor-flake` bin should do all that for you automatically.


Thanks! 😄

**Comment by ghost** [comment]
Thank you for the reply.
https://github.com/NickTomlin/protractor-flake/issues/79
