### ISSUE TITLE
add support for ts

### ISSUE THREAD

**Issue by gustavomick** [NickTomlin/protractor-flake#78]
if sourcemap is enabled failures report files with ts file but spec must execute js file.

**Comment by wswebcreation** [comment]
@gustavomick 

Can you clarify it more with an example?

**Comment by gustavomick** [comment]
Yeah np thnx. When parsing spec files to retry them. If sourcemap is enabled trace reporys myspec.ts and then prot flake tries aparently to execute that file instead of .js file.

**Comment by wswebcreation** [comment]
So if I understand you correctly, you are having `*.spec.ts` files, those are transpiled to `*.spec.js` files. The issues are logged to the console with `*.spec.ts` and passed on to `protractor-flake` to run them again. It can't find the files and it will run them all?

Can you also please provide:

- your `protractor.conf.js`
- console log that will show your problem

Tnx in advance

**Comment by westy92** [comment]
This may be helpful: https://www.npmjs.com/package/source-map-support

**Comment by theandrewlane** [comment]
Your .ts specs should be transpiled to .js... You might want to try jasmine-spec-reporter's customProcessors - you can read in the spec name, modify it (to match the transpiled js), and then write it to console. Either way, I don't think this is an issue with protractor-flake.

**Comment by NickTomlin** [comment]
I'm going to close this because I think Andrew is correct (and this issue is old).
