### ISSUE TITLE
Improve README.md with protractor.conf.js

### ISSUE THREAD

**Issue by benjaminapetersen** [NickTomlin/protractor-flake#82]
The current README.md install & usage instructions aren't exactly clear, do you require & use this within your current `protractor.conf.js`?   Initially I'm inclined to think there is a bit more to it as:

```JavaScript 
protractorFlake({
  protractorPath: '/path/to/protractor',
```
`protractorFlake` wants to know where protractor lives.  True?

**Comment by NickTomlin** [comment]
Your inclination is correct, flake handles executing protractor itself so this is not something that goes in your protractor config. 

 think this could definitely be clearer. Would a simple `// run-protractor-flake.js` at the top of the file or something like "in a separate file" help?

Can you think of other ways of clearing this up? I'd be more than happy to accept a README pr

**Comment by benjaminapetersen** [comment]
Well, I'm curious how one would setup a `grunt test` or `gulp test` or `npm run test` task to integrate this.  Perhaps even just clarifying how a `run-protractor-flake.js` would work along with an existing `protractor.conf.js`.  I haven't actually attempted to integrate this package yet, but it looks very promising for the types of issues I'm experiencing (running protractor in a Jenkins environment where timing issues can occasionally cause a set of tests to fail arbitrarily).

Thanks!

**Comment by ogiexela** [comment]
Which file should contain the js code from "Usage > programmatically"?
How is it invoked?

**Comment by NickTomlin** [comment]
@ogiexela Any Javascript file will do. E.g. if you were to write the contents of that example to `example.js` and then run `node example.js`.

I'm going to go ahead and close this issue. I'm happy to accept a PR to the README!
