### ISSUE TITLE
Feature Request: Expose attemptNo or allow code to be specified in beforeAttempts/afterAttempts

### ISSUE THREAD

**Issue by Tom-Hudson** [NickTomlin/protractor-flake#84]
I currently have a spec reporter which outputs an xml file that is then published to my CI after my tests have ran. At the moment, in `onPrepare` of my `protractor.conf` file, I delete any rogue xml files to ensure only one set of results are published from multiple flake runs. However, there may be a scenario where more tests pass on the the first/second run rather than the last, so I have now created a new method which checks the scores and deletes all reports but the one with the highest count of passes. The problem with this is that I have no way of cleaning up the directory for the very first run as no 'attemptNo' is exposed by `protractor-flake`.

So, I would like to request that the `attemptNo` is exposed so I can cleanup the directory if attempt is no. 1. Or, it would be good to be able to be able to specify functions like `beforeAttempts` and `afterAttempts` so there would be no need to expose the `attemptNo`, and I could just run the cleanup etc. within there.

**Comment by NickTomlin** [comment]
I think this makes a lot of sense, could you give me some pseudocode for how you'd use this? This could potentially be a `param` that we pass to protractor or an env variable that we set. I'd want to make sure we can do it in a way that wouldn't clash with protractor config.

**Comment by Tom-Hudson** [comment]
Glad you agree! To be honest I get a little twitchy with the thought of the attempt count being a Node environment variable as this value would persist if flake got stopped etc. It would also cause problems for shared CI/build servers with multiple builds unless you make the environment variable unique to the instance of flake running (not sure that's a good idea either)? In my opinion, it would be better as a `param` or just accessible from a `flake` instance:
```
onPrepare: () => { 
    if(flake.attemptNo == 1) {
        // Do cleanup
    }
}
```

But as I mentioned before, I would also be happy to put my code in functions passed to the protractor-flake config like so:

```
protractorFlake({
    parser: 'standard'
}, function(status, output) {
    process.exit(status);
}, function() {
    //beforeAttempts
}, function() {
    //afterAttempts
})
```

But the obvious drawback with the latter is that no 'protractor or jasmine stuff' will be available for use in either function. Also, if you go with this option, it would be nice if the functions could be callback managed (or accept a promised function) so time consuming operations can be performed synchronously (sorry for adding complexity).

Thanks!

**Comment by rasjani** [comment]
I guess my pr will address this as it will call protractor with --params.flake.iteration which then can be used in via browser.params.flake.iteration.

**Comment by Tom-Hudson** [comment]
@rasjani - yes it would! If @NickTomlin is happy then I would link the PR so this issue can be closed.

**Comment by rasjani** [comment]
https://github.com/NickTomlin/protractor-flake/pull/88

And its also already released.

**Comment by NickTomlin** [comment]
@rasjani thanks for reporting back here and for your PR! I'm going to go ahead and close this issue 😄
