### ISSUE TITLE
Running serve as part of Flake

### ISSUE THREAD

**Issue by ghost** [NickTomlin/protractor-flake#92]
Hi there!

I'm on Windows and Angular 6 - I was wondering if there is a way to run ng serve as part of the flake and close down once it's finished.
I'm trying to run flake on Teamcity. 

Thanks,
Shiva

**Comment by NickTomlin** [comment]
👋 Hi there!

I would do this in a wrapper script (or a background process) alongside protractor flake. I'm not a windows or teamcity user so I can't speak to exactly how that is done but I think it's possible. Hope that helps!

**Comment by NickTomlin** [comment]
I haven't seen any activity on this so I am going to close it for now. Thanks!

**Comment by ghost** [comment]
Thanks for the suggestion.
I created a script to run it, it's not ideal but does the job for now.
Thanks for the suggestion.

**Comment by NickTomlin** [comment]
Glad you found a solution, thanks!
