### ISSUE TITLE
seleniumAddress

### ISSUE THREAD

**Issue by gziebold** [NickTomlin/protractor-flake#97]
- Operating system and version 
- Node.js version 6.9.1
- Protractor version 5.4.1
- Protractor flake version latest 

Is there a trick to using the seleniumAddress parameter?  In the normal running of my tests I pass in the parameter of '--seleniumAddress http://localhost:4444/wd/hub' to override the default.  However when I try that same thing using protractor-flake it appears to resort to using the default:

`protractor-flake --parser cucumber --axeDev --seleniumAddress http://localhost:4444/wd/hub --max-attempts=1 -- features\support\cucumberConf.js
[15:38:30] I/launcher - Running 1 instances of WebDriver
[15:38:30] I/local - Starting selenium standalone server...
[15:39:05] E/launcher - Error: Error: Timed out waiting for the WebDriver server at http://172.25.173.50:56756/wd/hub
   at Error (native)
   at onError (C:\Users\gxzl\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\util.js:102:16)`

**Comment by NickTomlin** [comment]
If you want to pass selenium address to `protractor` you'll need to use `--` to not have `protractor-flake` treat it as an option:

E.g. from the README: 

```
# protractor-flake <protractor-flake-options> -- <options to be passed to protractor>
```
So a shortened example for your command (leaving out some other options) would look like:

```
protractor-flake --parser cucumber  -- --seleniumAddress http://localhost:4444/wd/hub features\support\cucumberConf.js
```

Hope that helps!

**Comment by NickTomlin** [comment]
Closing due to staleness
